# Generated by Django 4.2.8 on 2023-12-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=10, verbose_name='用戶名')),
                ('email', models.EmailField(max_length=254, verbose_name='電子郵件')),
                ('company', models.CharField(max_length=50, verbose_name='公司名')),
                ('birthdate', models.DateTimeField(verbose_name='生日')),
            ],
        ),
    ]
